# Generated by Django 4.2.30 on 2026-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('RUC', 'RUC'), ('DNI', 'DNI'), ('CE', 'Carné de Extranjería')], max_length=3, verbose_name='Tipo de Documento')),
                ('num_doc', models.CharField(max_length=15, verbose_name='Número de Documento')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
                'unique_together': {('tipo_doc', 'num_doc')},
            },
        ),
    ]
