# Generated by Django 4.2.30 on 2026-05-13 21:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=4, verbose_name='Serie')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito')], max_length=15, verbose_name='Tipo de Comprobante')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (Base Imponible)')),
                ('total_inafecto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Inafecto')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IGV (18%)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('xml_firmado', models.TextField(blank=True, verbose_name='XML Firmado')),
                ('hash_cpe', models.CharField(blank=True, max_length=64, verbose_name='Hash CPE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('tipo_nota', models.CharField(choices=[('01', 'Anulación de la operación'), ('02', 'Anulación por error en el RUC'), ('03', 'Corrección por error en la descripción'), ('04', 'Descuento global'), ('05', 'Descuento por ítem'), ('06', 'Devolución total'), ('07', 'Devolución por ítem')], default='01', max_length=2, verbose_name='Tipo de Nota')),
                ('monto_afectado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Afectado (S/.)')),
                ('comprobante_nota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_info', to='comprobantes.comprobante', verbose_name='Comprobante (Nota de Crédito)')),
                ('comprobante_referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='comprobantes.comprobante', verbose_name='Comprobante de Referencia')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
            },
        ),
        migrations.CreateModel(
            name='LogEnvioSUNAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('estado_respuesta', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EXCEPCION', 'Excepción')], default='PENDIENTE', max_length=10, verbose_name='Estado de Respuesta')),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10, verbose_name='Código de Respuesta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de Respuesta')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_envio', to='comprobantes.comprobante', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Log de Envío SUNAT',
                'verbose_name_plural': 'Logs de Envío SUNAT',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento aplicado a esta línea.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento (%)')),
                ('igv_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IGV Línea')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal Línea')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comprobantes.comprobante', verbose_name='Comprobante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_comprobante', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobante',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['tipo', 'estado'], name='comprobante_tipo_03a92b_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['fecha_emision'], name='comprobante_fecha_e_698c03_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['serie', 'numero'], name='comprobante_serie_21c88d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together={('serie', 'numero')},
        ),
    ]
