# Generated by Django 4.2.30 on 2026-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logenviosunat',
            name='codigo_respuesta',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código de Respuesta'),
        ),
        migrations.AlterField(
            model_name='logenviosunat',
            name='estado_respuesta',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EXCEPCION', 'Excepción')], default='PENDIENTE', max_length=20, verbose_name='Estado de Respuesta'),
        ),
    ]
