# Generated by Django 4.2.30 on 2026-05-13 21:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe contener exactamente 11 dígitos numéricos.')], verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('regimen_tributario', models.CharField(choices=[('GENERAL', 'Régimen General'), ('MYPE', 'Régimen MYPE Tributario'), ('RER', 'Régimen Especial de Renta'), ('RUS', 'Nuevo RUS')], default='GENERAL', max_length=50, verbose_name='Régimen Tributario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Factura'), ('B', 'Boleta'), ('FC', 'Nota de Crédito')], max_length=2, verbose_name='Tipo de Comprobante')),
                ('serie', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]\\d{3}$', 'La serie debe ser una letra seguida de 3 dígitos (ej: F001).')], verbose_name='Serie')),
                ('correlativo_actual', models.PositiveIntegerField(default=0, verbose_name='Correlativo Actual')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='empresa.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Serie de Comprobante',
                'verbose_name_plural': 'Series de Comprobantes',
                'ordering': ['tipo', 'serie'],
                'unique_together': {('empresa', 'tipo', 'serie')},
            },
        ),
    ]
